### ISSUE TITLE
Support for Private IPs (Not using Tier 0 ips) for Control Plane LB

### ISSUE THREAD

**Issue by ekarlso** [vmware/cluster-api-provider-cloud-director#149]
### Is your feature request related to a problem? Please describe.

Security requirements say you should place ControlPlane on private networks and not using Tier0 routable on the internetl.

### Describe the solution you'd like

Be able to have Control Plane LB only within the Virtual Network inside of VCD and not exposed on a Tier 0. This pattern is achieved with Private Endpoints or similar concepts on Azure where they advise you to have the ControlPlane internal only not exposing it on the internet.

### Describe alternatives you've considered

Having private ips defined by provider like 10.x.x.x. on the tier0 but that will not work maybe with things like S2S vpn etc?

**Comment by vxav** [comment]
Agreed, api access should be achieved over VPN into the tenant via a private VIP and svc type load balancer on the T0.

**Comment by mkriegs** [comment]
atm the placement of the VIPs from AVI are only possible on T1 LVL -> so the integration/placement of the VIPs need to be possible at vAPP Networks/ Org Networks or ISOLATED Networks.
If this is possible you should be able to deploy Cluster into vAPP Network Firewall with separate T1 connect to ORG Network. so you can use T1 as Global Firewall and the vApp FW for each K8s Cluster.
But all this staff need to be done on VCD level not on the CAPVCD level

**Comment by arunmk** [comment]
We should be able to just use the one-arm IP and add it to the list of SANs (and also skip creation of dnat rule). I will try it out.

**Comment by vxav** [comment]
That'd be great if we had the option to skip `vipSubnet: ${VCD_VIP_CIDR}` for the creation of the kube-api so it works even if there are no T0 IPs free.

**Comment by arunmk** [comment]
@vxav @ekarlso if we do this, the only way to ***create*** and access the cluster will be using a VM on the same Tier1 network. Is that acceptable to you?

**Comment by vxav** [comment]
Yes that is fine, we’ll deploy a bastion in the tenant. I think having both options is good.
