### ISSUE TITLE
Reference a secret instead of credentials/refresh token

### ISSUE THREAD

**Issue by vxav** [vmware/cluster-api-provider-cloud-director#168]
### Is your feature request related to a problem? Please describe.

At the moment, credentials or a refresh token must be set in the cluster manifest to deploy a workload cluster.
The credentials/refreshToken are in clear text in the VCDCluster object.

### Describe the solution you'd like

Support for `IdentityRef ` where the user has an identity secret in his/her namespace which is referenced in the cluster manifest in the `userContext` section.

**Comment by abaruni** [comment]
https://github.com/vmware/cluster-api-provider-cloud-director/pull/169
