### ISSUE TITLE
Workload cluster secret is wrong when deployed with secretRef

### ISSUE THREAD

**Issue by vxav** [vmware/cluster-api-provider-cloud-director#171]
### Describe the bug

When deploying a workload cluster with `secretRef`, the `vcloud-basic-auth` secret contains the wrong information. Which means the CPI cannot connect to VCD and unset the `node.cloudprovider.kubernetes.io/uninitialized: true` taint on the nodes.

It contains the base64 encoded org name followed by a forward slash. password and refreshToken are both empty.

Which points to the following:
- Is UserCredentialsContext correct here? https://github.com/vmware/cluster-api-provider-cloud-director/blob/07f16d2d5c3663e739ae7e9bed0e0b9c73b6c186/controllers/vcdmachine_controller.go#L511-L512
- Clusters use `secretRef `in `userContext>secretRef`. 
https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/examples/capi-quickstart.yaml#L51

When deploying a cluster without secretRef (like in 0.5.1) and with only the refreshToken, the refreshToken is correctly in the secret in the WC, however the orgname/ is still in the username (not a blocker but buggy).

### Reproduction steps

1. Create a secret in the management cluster
2. Deploy a WC with `secretRef`
3. Change context to the WC and check the following:

```
k describe pod -n kube-system vmware-cloud-director-ccm-b5d58cd57-nnrqk

k get secrets -n kube-system vcloud-basic-auth -oyaml
```

### Expected behavior

The `vcloud-basic-auth` secret contains the information specified in `secretRef`.

**Comment by abaruni** [comment]
@vxav thanks for finding this and opening this issue. i will have a PR up shortly to fix this. i'll also take a look into fixing the username issue when using the refreshToken. thanks!

**Comment by vxav** [comment]
Couple thoughts following chat with @arunmk 

- Creating the secret within the cluster manifest creates a chicken and egg scenario when deleting the cluster resources with `k delete -f cluster-manifest.yaml` as the secret gets deleted and the controller cannot auth to VCD to delete resources.
- It seems secretRef isn't prioritized over creds/token when both are specified. Although this may be a non-problem if `userCredentialContext` ends up disappearing.

**Comment by abaruni** [comment]
We are not creating it within the cluster manifest.

The secret is prioritized over the credentials when both are specified

**Comment by vxav** [comment]
I was referencing this section of the example manifest. https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/examples/capi-quickstart.yaml#L29

**Comment by abaruni** [comment]
Yes. I'm saying it is just an example to show correct usage. You should be creating and deleting the secret independently of the cluster. In addition, you should not be deleting the cluster using the manifest. You should just delete the cluster object. The controllers will do the rest

**Comment by vxav** [comment]
Thanks for clarifying that, it does make sense.

**Comment by abaruni** [comment]
Okay, great. I'll add a comment to the example manifest to clarify that
