### ISSUE TITLE
Version K8S cluster

### ISSUE THREAD

**Issue by TimTinneveld** [vmware/cluster-api-provider-cloud-director#271]
### Is your feature request related to a problem? Please describe.

Hi,

Are newer K8S versions also supported? The ReadME tells me it is only supported until version 1.21.X.

 

### Describe the solution you'd like

Being able to upgrade to newer version than 1.21.x.

**Comment by jlemoingora** [comment]
I'm also very interested on that point.

TKG 1.6.0 supports K8S 1.23.8 and with CAPVCD we are stuck to 1.21 ?
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-release-notes.html

Is it plan to have more versions supported ?

**Comment by janaurka** [comment]
Hey @Anirudh9794 

Do you have en ETA when you plan to introduce support for TKG 2.x which at least supports Kubernetes 1.24.X (which will be [EOL in roughly 2 months](https://kubernetes.io/releases/#release-v1-24))?

Running on TKG 1.6.1 which only supports 1.23.X which is EOL for more then [two months](https://endoflife.date/kubernetes) is not an option unfortunately.

**Comment by Anirudh9794** [comment]
Hi @janaurka,

Sorry for the confusion, the README tells the version of K8s which is qualified by us. 

1.24 & 1.25 from TKG 2.x should work with CAPVCD 1.0.1 and later versions.

**Comment by Anirudh9794** [comment]
We have added a note in the README.md of main branch that the versions in the list are the ones which are qualified by us.

Closing this ticket for now. If you have any follow ups, please feel free to re-open the ticket
