### ISSUE TITLE
Wrong cloud-init datasource used. Nodes get stuck at bootstrapping phase.

### ISSUE THREAD

**Issue by jaymzmac** [vmware/cluster-api-provider-cloud-director#302]
### Describe the bug

My understanding is that the bootstrapping nodes in CAPVCD leverages the VMware GuestInfo Cloud-Init datasource.

However, during our testing we see that VMs cloned from our TKG OVA template (ubuntu-2004-kube-v1.21.14+vmware.2) use the OVF Cloud-Init datasource, causing the nodes to get stuck in the bootstrapping phase.

root@ubuntu-2004-001:~# cloud-init status --long
status: done
time: Tue, 18 Oct 2022 09:42:29 +0000
detail:
DataSourceOVF [seed=com.vmware.guestInfo]

root@ubuntu-2004-001:~# DEBUG_LEVEL=2 DI_LOG=stderr /usr/lib/cloud-init/ds-identify --force
Checking for datasource 'OVF' via 'dscheck_OVF'
Found guestinfo transport.
check for 'OVF' returned found
Checking for datasource 'VMware' via 'dscheck_VMware'
check for 'VMware' returned found
Found 2 datasources found=all: OVF VMware

If we manually disable OVF as a Cloud-Init datasource in the cloned VM and then reboot, we see that the VM is then successfully bootstrapped as expected.

root@demo-work-pool-1-78f97b8f69-2mj82:~# date
Tue 18 Oct 2022 11:49:05 AM UTC

kubectl describe vcdmachines demo-work-pool-1-ptsrt
    Last Transition Time:  2022-10-18T11:25:17Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-10-18T11:25:17Z
    Status:                True
    Type:                  BootstrapExecSucceeded
    Last Transition Time:  2022-10-18T09:39:28Z
    Status:                True
    Type:                  ContainerProvisioned

### Reproduction steps

1. Upload TKG OVA as an OVF template to a Cloud Director Catalog
2. Deploy a CAPVCD cluster referencing the TKG OVA
3. Observe that the Cloud-Init datasource used is OVF and not GuestInfo.

### Expected behavior

1. Upload TKG OVA as an OVF template to a Cloud Director Catalog
2. Deploy a CAPVCD cluster referencing the TKG OVA
3. Cloned VM uses the GuestInfo Cloud-Init datasource by default so no manual intervention is needed to bootstrap the nodes.

**Comment by arunmk** [comment]
This is fixed in CAPVCD 1.0.1.

**Comment by Anirudh9794** [comment]
Closing this issue based on the above comment
