### ISSUE TITLE
Pod Security Policy is removed from Kubernetes 1.25

### ISSUE THREAD

**Issue by vxav** [vmware/cluster-api-provider-cloud-director#311]
### Is your feature request related to a problem? Please describe.

Running CAPVCD on K8s 1.25 isn't possible at the moment as Pod Security Policies (PSP) are [removed](https://kubernetes.io/docs/concepts/security/pod-security-policy/).

### Describe the solution you'd like

Make CAPVCD compatible with Kubernetes 1.25 by using Pod Security Standards (PSS) if this is suitable.

**Comment by Anirudh9794** [comment]
Hi @vxav ,
Can you please explain more on what is expected from CAPVCD with PSP being removed?
Should we be expecting an admission level set on the CAPVCD namespace?
