### ISSUE TITLE
Controller doesn't put hub type data into older type annotation

### ISSUE THREAD

**Issue by bavarianbidi** [vmware/cluster-api-provider-cloud-director#355]
### Describe the bug

To not loose any kind of information when introducing a new API version, CAPI (and most of their infraprovider implementations) are using a `hub-spoke-hub` model to transfer the `spec` data between API versions.

This data is stored in the resource type as annotation with the name `cluster.x-k8s.io/conversion-data`.

E.g. having a cluster where CAPIs cluster CRD is set to `v1beta1`, e.g a
`k get cluster.v1alpha4.cluster.x-k8s.io mycluster -o=jsonpath='{.metadata.annotations.cluster\.x-k8s\.io/conversion-data}' | jq -r`
will result in below output

<details>
  <summary>expand to see result</summary>

```json
{
  "apiVersion": "cluster.x-k8s.io/v1beta1",
  "kind": "Cluster",
  "spec": {
    "clusterNetwork": {
      "pods": {
        "cidrBlocks": [
          "192.168.0.0/16"
        ]
      }
    },
    "controlPlaneEndpoint": {
      "host": "glippy-xxxx.azure.com",
      "port": 6443
    },
    "controlPlaneRef": {
      "apiVersion": "controlplane.cluster.x-k8s.io/v1beta1",
      "kind": "KubeadmControlPlane",
      "name": "mycluster",
      "namespace": "default"
    },
    "infrastructureRef": {
      "apiVersion": "infrastructure.cluster.x-k8s.io/v1beta1",
      "kind": "AzureCluster",
      "name": "mycluster",
      "namespace": "default"
    }
  },
  "status": {
    "conditions": [
      {
        "lastTransitionTime": "2022-11-24T06:44:49Z",
        "reason": "WaitingForKubeadmInit",
        "severity": "Info",
        "status": "False",
        "type": "Ready"
      },
      {
        "lastTransitionTime": "2022-11-24T06:34:32Z",
        "message": "Waiting for control plane provider to indicate the control plane has been initialized",
        "reason": "WaitingForControlPlaneProviderInitialized",
        "severity": "Info",
        "status": "False",
        "type": "ControlPlaneInitialized"
      },
      {
        "lastTransitionTime": "2022-11-24T06:44:49Z",
        "reason": "WaitingForKubeadmInit",
        "severity": "Info",
        "status": "False",
        "type": "ControlPlaneReady"
      },
      {
        "lastTransitionTime": "2022-11-24T06:37:41Z",
        "status": "True",
        "type": "InfrastructureReady"
      }
    ],
    "controlPlaneReady": false,
    "failureDomains": {
      "1": {
        "controlPlane": true
      },
      "2": {
        "controlPlane": true
      },
      "3": {
        "controlPlane": true
      }
    },
    "infrastructureReady": true,
    "observedGeneration": 2,
    "phase": "Provisioned"
  }
}
```

</details>

Not having the hub-spoke-hub model in place will lead to following issue:
1. Cluster-CRs got created with the current default  API version (e.g. `v1alpha4`)
2. controllers are updated and serving the new API version (`v1beta1`)
3. User edit the `CR` via `kubectl edit` (point to the new version) and e.g. adding values into a newly introduced field
4. Controller reconcile the cluster with the new change
5. If the newly introduced field doesn't have a counterpart in the old API version it will be cleared (e.g. via an empty string)
6. As the CR is still stored in etcd in the old version it doesn't contain any details about how the spec should look like in the new version
7. Controller reconcile the cluster again, getting the CR in the old API version and all the previously defined values are gone.

`CAPZ` example of the missing code in `CAPVCD`:
* [CAPZ for `v1beta1` to `v1alpha4`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1alpha4/azurecluster_conversion.go#L104-L106)
* [CAPZ for `v1alpha4` to `v1beta1`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1alpha4/azurecluster_conversion.go#L35-L39)

useful Links:
* [SIG Cluster Lifecycle - ClusterAPI - API conversion code walkthrough Video](https://www.youtube.com/watch?v=Mk14N4SelNk)
* [upstream tracking issue for documentation improvements](https://github.com/kubernetes-sigs/cluster-api/issues/6464)

### Reproduction steps

1. Deploy controller and CRDs in `v1alpha4` version
2. Create a cluster
3. Update controller and CRDs to new version `v1beta1`
4. run `kubectl get vcdcluster.v1alpha4.infrastructure.cluster.x-k8s.io` to get the cluster-spec in the etcd stored version

### Expected behavior

```
kubectl get vcdcluster.v1alpha4.infrastructure.cluster.x-k8s.io <CLUSTERNAME> -o=jsonpath='{.metadata.annotations.cluster\.x-k8s\.io/conversion-data}' | jq -r 
```

should have contain the `vcdcluster.spec` in `v1beta1` version

**Comment by Anirudh9794** [comment]
@bavarianbidi The PR to make these changes is now merged. So I will close the issue.
