### ISSUE TITLE
Not being able to pull the image

### ISSUE THREAD

**Issue by jonkerj** [vmware/cluster-api-provider-cloud-director#360]
### Describe the bug

I installed capvcd per instructions, and the pods are not able to run:

```
Failed to pull image "harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b": rpc error: code = Unknown desc = failed to pull and unpack image "harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b": failed to resolve reference "harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b": failed to do request: Head "https://harbor-repo.vmware.com/v2/vcloud/cluster-api-provider-cloud-director/manifests/main-branch.6409b2b": dial tcp: lookup harbor-repo.vmware.com: No address associated with hostname
```

### Reproduction steps

Use `nslookup` to resolve `harbor-repo.vmware.com`:

```
$ host -v harbor-repo.vmware.com
Trying "harbor-repo.vmware.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56027
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;harbor-repo.vmware.com.		IN	A

;; AUTHORITY SECTION:
vmware.com.		2255	IN	SOA	dns1.p05.nsone.net. hostmaster.nsone.net. 1660090488 3600 600 604800 3600

Received 105 bytes from 172.21.42.1#53 in 4 ms
Trying "harbor-repo.vmware.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42920
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;harbor-repo.vmware.com.		IN	AAAA

;; AUTHORITY SECTION:
vmware.com.		2255	IN	SOA	dns1.p05.nsone.net. hostmaster.nsone.net. 1660090488 3600 600 604800 3600

Received 105 bytes from 172.21.42.1#53 in 3 ms
Trying "harbor-repo.vmware.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32666
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;harbor-repo.vmware.com.		IN	MX

;; AUTHORITY SECTION:
vmware.com.		3592	IN	SOA	dns1.p05.nsone.net. hostmaster.nsone.net. 1660090488 3600 600 604800 3600

Received 105 bytes from 172.21.42.1#53 in 3 ms
```

So, the FQDN is not resolvable at all.

### Expected behavior

I expected to be able to pull the image.

### Additional context

I did some digging, and it seems there are images present at `projects.registry.vmware.com`:

```
$ skopeo list-tags docker://projects.registry.vmware.com/vmware-cloud-director/cluster-api-provider-cloud-director
{
    "Repository": "projects.registry.vmware.com/vmware-cloud-director/cluster-api-provider-cloud-director",
    "Tags": [
        "0.5.0",
        "0.5.1",
        "1.0.0",
        "1.0.0-beta",
        "main-branch",
        "main-branch.282edbd"
    ]
}
```

It does not contain the suggested tag (`main-branch:6409b2b`), though.

**Comment by thomaspaulsen** [comment]
Got the same problem, it seems like the links to the images in the infrastructure-components.yaml are either internal VMware links anyone outside is unable to get, or something changed.
`grep -rnw /root -e 'harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b'
/root/cluster-api-provider-cloud-director/templates/infrastructure-components.yaml:1166:        image: harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b
/root/cluster-api-provider-cloud-director/config/manager/manager.yaml:25:        image: harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.6409b2b
`

**Comment by lzichong** [comment]
Hi @thomaspaulsen and @jonkerj, this is expected because `main` branch is what we use for development, and harbor-repo.vmware.com is what we use internally to host our images during dev/testing. Rather than using the development branch, please use the official version of CAPVCD from tag `v1.0.0` as this was release: https://github.com/vmware/cluster-api-provider-cloud-director/tree/1.0.0. This will pull images from `projects.registry.vmware.com` which is publicly accessible.

**Comment by biyiklioglu** [comment]
The documentation in [CLUSTERCTL.md](https://github.com/vmware/cluster-api-provider-cloud-director/blob/d05d033021f9e1152a8922ef6b720c6044b6153d/docs/CLUSTERCTL.md?plain=1#L9) is misleading.

In the Set up section item 2. reads:

Copy the contents from [templates directory](https://github.com/vmware/cluster-api-provider-cloud-director/tree/main/templates) to ~/infrastructure-vcd/v1.0.0/

with a direct link to the `main` branch instead of the `1.0.0` tag.

The link 

https://github.com/vmware/cluster-api-provider-cloud-director/tree/main/templates

should be changed to 

https://github.com/vmware/cluster-api-provider-cloud-director/tree/1.0.0/templates

and it should explicitly be stated that the files must be copied from the 1.0.0 tag.

**Comment by lzichong** [comment]
Hi @biyiklioglu, apologies for the delays. You are looking at the documentation off of `main` branch and as `main` is in development, it is subject to change/documentations will can go stale. `main` will reference things in `main` as newer things may get merged in and needs to be referenced for testing. Please use CLUSTERCTL documentation from `1.0.z` branch or tag `1.0.0` from here to reference to correct documentation pointing to `1.0.0`: https://github.com/vmware/cluster-api-provider-cloud-director/blob/1.0.0/docs/CLUSTERCTL.md, sorry for the confusion, I hope this provides some clarity.

**Comment by biyiklioglu** [comment]
Thanks for the clarification. 
However, it would be useful to add a warning to the CLUSTERCTL.md under the main branch that people should follow the document from a specific branch.
Otherwise this will continue confusing the new comers.

**Comment by lzichong** [comment]
> Thanks for the clarification. However, it would be useful to add a warning to the CLUSTERCTL.md under the main branch that people should follow the document from a specific branch. Otherwise this will continue confusing the new comers.

Hello @biyiklioglu, sorry for the delays and thanks for the feedback. We have updated the documentation in CLUSTERCTL.md under main and now refers to components in `1.0.2` tags for setting up `1.0.2` and `main` branch for setting up things in the `main`.

**Comment by lzichong** [comment]
Closing this issue as documentation has been updated and the original issue was attempting to pull image on main.
