### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by miskaste** [vmware/cluster-api-provider-cloud-director#444]
### Describe the bug

I'm using vCloud Director "Kubernetes Container Cluster" plugin to deploy Tanzu cluster. Cluster Bootstrap process is failing because script can't download template from provided link. I checked this link from my browser and it's not exist. Something is broken with tags in github.

I think affected is every customer who will use CSE 4.0.3 and will try to deploy Tanzu cluster!

### Reproduction steps

1. Install Container Extension Service v4.0.3
2. Deploy vCD plugin
3. Configure CES server
4. Configure vCloud Director
5. Try to create Tanzu cluster from tenant portal.
...
![1](https://github.com/vmware/cluster-api-provider-cloud-director/assets/133357309/8d0fb6c9-280e-4978-9f16-69bc5e1c515d)

![2](https://github.com/vmware/cluster-api-provider-cloud-director/assets/133357309/2f79bebe-8316-4ca3-a028-93e37e064486)

![3](https://github.com/vmware/cluster-api-provider-cloud-director/assets/133357309/0c106546-c609-47c3-b066-019ef6dd6770)

![4](https://github.com/vmware/cluster-api-provider-cloud-director/assets/133357309/bb1e5f70-68a6-4dd7-b2c4-a69bcea7edc8)

### Expected behavior

Script will download files from github

**Comment by JustasKrik** [comment]
Which version of CAPVCD have you set in configure CSE server section?

**Comment by miskaste** [comment]
I have here value 1.0.0.

**Comment by JustasKrik** [comment]
Set it to 1.0.1 as CSE 4.0.3 for tanzu 1.6.1 requires CAPVCD to be. 1.0.1 version

**Comment by miskaste** [comment]
Thank you, that was what was needed!
