### ISSUE TITLE
typo in version in an invalid RDE version error

### ISSUE THREAD

**Issue by msdolbey** [vmware/cluster-api-provider-cloud-director#540]
### Describe the bug

This is really a small thing that I encountered in the wild.
Just a typo (`verison`) when there was an invalid RDE version:

```
I1031 21:04:40.488355       1 gateway.go:69] Obtained Gateway [standard] for Network Name..."name": "dolbcd-2", "reconcileID": "1470ac9d-2e72-4183-a4c9-b255524438c1", "error": "invalid RDE verison [NO_RDE_] derived"}..."error": "error validating derived infraID and RDE version with VCDCluster status: invalid RDE verison [NO_RDE_] derived", "errorVerbose": "invalid RDE verison [NO_RDE_] derived\nerror validating derived infraID and RDE version with VCDCluster...
```

This just fixes that typo for users in the logs.

### Reproduction steps

1. Create a scneario where there is an invalid RDE verison
2. Check the capvcd logs
3. ctrl+f for `verison` and see this error instead of having it say version.

### Expected behavior

The errors shouldn't have typos in it

### Additional context

Totally minor issue. Just caught my (more specifically, my co-worker's) eye.

**Comment by Anirudh9794** [comment]
closing this issue as the PR for the change is merged
