### ISSUE TITLE
CAPVCD Should support service accounts and api tokens

### ISSUE THREAD

**Issue by rouke-broersma** [vmware/cluster-api-provider-cloud-director#665]
### Is your feature request related to a problem? Please describe.

Username & Password should not be shared with automation software in this day and age. Cloud Director supports service accounts and api tokens, CAPVCD should also support this auth method to increase security.

### Describe the solution you'd like

Support cloud director service accounts and api tokens as auth method: https://blogs.vmware.com/cloudprovider/2022/03/cloud-director-api-token.html

**Comment by rouke-broersma** [comment]
> ### Is your feature request related to a problem? Please describe.
> Username & Password or refresh token for personal accounts should not be shared with automation software in this day and age. Cloud Director supports service accounts and api tokens, CAPVCD should also support this auth method to increase security.
> 
> ### Describe the solution you'd like
> Support cloud director service accounts and api tokens as auth method: https://blogs.vmware.com/cloudprovider/2022/03/cloud-director-api-token.html
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

**Comment by arunmk** [comment]
The `refreshToken` field of capvcd can take the api token of cloud director. In fact, the api-token feature was planned for capvcd. The username and password is for quick development modes only. We recommend the use of api-tokens in production.

**Comment by rouke-broersma** [comment]
From this blog post I learned that refresh token in cloud director terms means api token: https://vxav.fr/2022-09-18-vmware-cloud-director-10.3-refresh-token-and-how-to-use-them/
