### ISSUE TITLE
Use different account for workload clusters with limited permissions

### ISSUE THREAD

**Issue by vxav** [vmware/cluster-api-provider-cloud-director#81]
### Is your feature request related to a problem? Please describe.

The idea would be to deploy workload clusters with a user equipped with a reduced permissions set compared to the management cluster.

### Describe the solution you'd like

Create a CAPVCD role with  [Rights required for CPI](https://github.com/vmware/cloud-provider-for-cloud-director#additional-rights-for-cpi) and [Rights required for CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver#additional-rights-for-csi).
Create a user with this role and deploy workload clusters with this user.

**Comment by arunmk** [comment]
@vxav we already do use a different account. The account used is the one mentioned in the capi yaml.

This is the location where the account for the management cluster is to be specified: Step 2.iii of https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/docs/MANAGEMENT_CLUSTER.md#initialize-the-cluster-with-cluster-api

This is the location where the account for the workload cluster is to be specified: https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/examples/capi-quickstart.yaml#L36-L39

Does the current situation solve your requirement?

**Comment by vxav** [comment]
Does the tenant user creating the workload cluster require the exact same set of permissions as the users that initializes CAPVCD?
Does it need `Right 'Full Control: VMWARE:CAPVCDCLUSTER'` ?

**Comment by arunmk** [comment]
Yes, the tenant user requires the `Right 'Full Control: VMWARE:CAPVCDCLUSTER'` right. This right enables the tenant user to be able to read and write from the private sections of the RDE. (The tenant user who is the k8s cluster administrator needs this right)
